apiVersion: v1
data:
  db_migration.sh: |
    #!/bin/sh

    echo "MONGODB_URI=$MONGODB_URI" >.env
    npm run migrate:db:up
    rm .env
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: backend
  name: backend-cm2
