apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    io.kompose.service: backend
spec:
  selector:
    io.kompose.service: backend
  ports:
    - protocol: TCP
      port: 3000 # Port exposed internally
      targetPort: 3000 # Port in the container
      nodePort: 32000 # Optional: Expose frontend-service on port 32001 (within the NodePort range)
  type: NodePort # This can be LoadBalancer
