apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yaml -f ../../mongodb/compose.yaml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      io.kompose.service: backend
  template:
    metadata:
      labels:
        io.kompose.service: backend
    spec:
      containers:
        - args:
            - node
            - dist/main
          command:
            - loop_entrypoints.sh
            - docker-entrypoint.sh
            # - /bin/sh
            # - -c
            # - "sleep 3600"
          env:
            - name: ADMIN_GROUPS
              valueFrom:
                configMapKeyRef:
                  key: ADMIN_GROUPS
                  name: backend-env
            - name: CREATE_DATASET_GROUPS
              valueFrom:
                configMapKeyRef:
                  key: CREATE_DATASET_GROUPS
                  name: backend-env
            - name: DELETE_GROUPS
              valueFrom:
                configMapKeyRef:
                  key: DELETE_GROUPS
                  name: backend-env
            - name: EXPRESS_SESSION_SECRET
              valueFrom:
                configMapKeyRef:
                  key: EXPRESS_SESSION_SECRET
                  name: backend-env
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  key: JWT_SECRET
                  name: backend-env
            - name: MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  key: MONGODB_URI
                  name: backend-env
            - name: PROPOSAL_GROUPS
              valueFrom:
                configMapKeyRef:
                  key: PROPOSAL_GROUPS
                  name: backend-env
            - name: SAMPLE_GROUPS
              valueFrom:
                configMapKeyRef:
                  key: SAMPLE_GROUPS
                  name: backend-env
            - name: SITE
              valueFrom:
                configMapKeyRef:
                  key: SITE
                  name: backend-env
          image: ghcr.io/scicatproject/backend-next:v4.5.1
          livenessProbe:
            exec:
              command:
                # - wget --spider -Y off 'http://127.0.0.1:3000/api/v3/health'
                - /bin/sh
                - -c
                # - "curl --silent --fail http://127.0.0.1:3000/api/v3/health"
                - "nc -zv 127.0.0.1 3000"
            failureThreshold: 5
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 10
          name: backend
          volumeMounts:
            - mountPath: /home/node/app/functionalAccounts.json
              name: backend-cm0
              subPath: functionalAccounts.json
            - mountPath: /usr/local/bin/loop_entrypoints.sh
              name: backend-cm1
              subPath: loop_entrypoints.sh
            - mountPath: /docker-entrypoints/0.sh
              name: backend-cm2
              subPath: 0.sh
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: functionalAccounts.json
                path: functionalAccounts.json
            name: backend-cm0
          name: backend-cm0
        - configMap:
            items:
              - key: loop_entrypoints.sh
                path: loop_entrypoints.sh
            name: backend-cm1
            defaultMode: 0755
          name: backend-cm1
        - configMap:
            items:
              - key: db_migration.sh
                path: 0.sh
            name: backend-cm2
          name: backend-cm2
