apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: backendv4-mongodb-data
  name: backendv4-mongodb-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
