apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yaml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: mongodb
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongodb

  template:
    metadata:
      labels:
        io.kompose.service: mongodb
    spec:
      containers:
        - env:
            - name: BE_VERSION
              value: v4
          image: mongo:8.0
          name: mongodb
          volumeMounts:
            - mountPath: /data/db
              name: backendv4-mongodb-data
            - mountPath: /docker-entrypoint-initdb.d/init.sh
              name: mongodb-cm1
              subPath: init.sh
            - mountPath: /seed
              name: mongodb-cm2
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
      restartPolicy: Always
      volumes:
        - name: backendv4-mongodb-data
          persistentVolumeClaim:
            claimName: backendv4-mongodb-data
        - configMap:
            items:
              - key: init.sh
                path: init.sh
            name: mongodb-cm1
          name: mongodb-cm1
        - configMap:
            name: mongodb-cm2
          name: mongodb-cm2
