apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: letsencrypt-proxy-data
  name: letsencrypt-proxy-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
