apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: proxy
  name: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: proxy
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f compose.yaml
        kompose.version: 1.34.0 (cbf2835db)
        traefik.http.services.proxy.loadbalancer.server.port: "8080"
      labels:
        io.kompose.service: proxy
    spec:
      containers:
        - args:
            - sh
            - -c
            - touch /config/traefik.yaml; traefik
          env:
            - name: BE_VERSION
              valueFrom:
                configMapKeyRef:
                  key: BE_VERSION
                  name: env
            - name: COMPOSE_PROJECT_NAME
              value: test_k8s_conversion
            - name: TRAEFIK_API_INSECURE
              valueFrom:
                configMapKeyRef:
                  key: TRAEFIK_API_INSECURE
                  name: proxy-env
            - name: TRAEFIK_CERTIFICATESRESOLVERS_LERESOLVER_ACME_CASERVER
              valueFrom:
                configMapKeyRef:
                  key: TRAEFIK_CERTIFICATESRESOLVERS_LERESOLVER_ACME_CASERVER
                  name: proxy-tls-env
            - name: TRAEFIK_CERTIFICATESRESOLVERS_LERESOLVER_ACME_EMAIL
              valueFrom:
                configMapKeyRef:
                  key: TRAEFIK_CERTIFICATESRESOLVERS_LERESOLVER_ACME_EMAIL
                  name: proxy-tls-env
            - name: TRAEFIK_CERTIFICATESRESOLVERS_LERESOLVER_ACME_STORAGE
              valueFrom:
                configMapKeyRef:
                  key: TRAEFIK_CERTIFICATESRESOLVERS_LERESOLVER_ACME_STORAGE
                  name: proxy-env
            - name: TRAEFIK_CERTIFICATESRESOLVERS_LERESOLVER_ACME_TLSCHALLENGE
              valueFrom:
                configMapKeyRef:
                  key: TRAEFIK_CERTIFICATESRESOLVERS_LERESOLVER_ACME_TLSCHALLENGE
                  name: proxy-env
            - name: TRAEFIK_ENTRYPOINTS_WEBSECURE_ADDRESS
              valueFrom:
                configMapKeyRef:
                  key: TRAEFIK_ENTRYPOINTS_WEBSECURE_ADDRESS
                  name: proxy-env
            - name: TRAEFIK_ENTRYPOINTS_WEBSECURE_HTTP_TLS_CERTRESOLVER
              valueFrom:
                configMapKeyRef:
                  key: TRAEFIK_ENTRYPOINTS_WEBSECURE_HTTP_TLS_CERTRESOLVER
                  name: proxy-env
            - name: TRAEFIK_ENTRYPOINTS_WEB_ADDRESS
              valueFrom:
                configMapKeyRef:
                  key: TRAEFIK_ENTRYPOINTS_WEB_ADDRESS
                  name: proxy-env
            - name: TRAEFIK_ENTRYPOINTS_WEB_ASDEFAULT
              valueFrom:
                configMapKeyRef:
                  key: TRAEFIK_ENTRYPOINTS_WEB_ASDEFAULT
                  name: proxy-env
            # - name: TRAEFIK_PROVIDERS_DOCKER
            #   valueFrom:
            #     configMapKeyRef:
            #       key: TRAEFIK_PROVIDERS_DOCKER
            #       name: proxy-env
            # - name: TRAEFIK_PROVIDERS_DOCKER_CONSTRAINTS
            #   valueFrom:
            #     configMapKeyRef:
            #       key: TRAEFIK_PROVIDERS_DOCKER_CONSTRAINTS
            #       name: proxy-env
            # - name: TRAEFIK_PROVIDERS_DOCKER_DEFAULTRULE
            #   valueFrom:
            #     configMapKeyRef:
            #       key: TRAEFIK_PROVIDERS_DOCKER_DEFAULTRULE
            #       name: proxy-env
            - name: TRAEFIK_PROVIDERS_FILE_FILENAME
              valueFrom:
                configMapKeyRef:
                  key: TRAEFIK_PROVIDERS_FILE_FILENAME
                  name: proxy-env
            - name: TRAEFIK_PROVIDERS_KUBERNETESINGRESS
              valueFrom:
                configMapKeyRef:
                  key: TRAEFIK_PROVIDERS_KUBERNETESINGRESS
                  name: proxy-env
          image: traefik:v3.2
          livenessProbe:
            exec:
              command:
                - /https_services.sh
            failureThreshold: 5
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 30
          name: proxy
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 443
              protocol: TCP
          volumeMounts:
            - mountPath: /letsencrypt
              name: letsencrypt-proxy-data
            - mountPath: /https_services.sh
              name: proxy-cm2
              subPath: https_services.sh
            - mountPath: /config/traefik.pre.yaml
              name: proxy-cm3
              subPath: traefik.pre.yaml
          resources:
            requests:
              memory: "256Mi" # Adjust as necessary
              cpu: "500m" # Adjust as necessary
            limits:
              memory: "512Mi" # Adjust as necessary
              cpu: "1" # Adjust as necessary
      restartPolicy: Always
      volumes:
        - name: letsencrypt-proxy-data
          persistentVolumeClaim:
            claimName: letsencrypt-proxy-data
        - configMap:
            items:
              - key: https_services.sh
                path: https_services.sh
            name: proxy-cm2
            defaultMode: 0755
          name: proxy-cm2
        - configMap:
            items:
              - key: tls.yaml
                path: traefik.pre.yaml
            name: proxy-cm3
          name: proxy-cm3
