apiVersion: v1
data:
  merge_json.sh: |
    #!/bin/sh

    apk update && apk add jq gettext

    jq -s 'reduce .[] as $item ({}; . * $item)' /config/*.json | envsubst \
        > "${CONFIG_DIR:-/usr/share/nginx/html/assets}"/config.json
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: frontend
  name: frontend-cm3
