apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    io.kompose.service: frontend
spec:
  selector:
    io.kompose.service: frontend
  ports:
    - protocol: TCP
      port: 80 # Port exposed to the outside world
      targetPort: 80 # Port in the container
      nodePort: 32001 # Optional: Expose frontend-service on port 32001 (within the NodePort range)
  type: NodePort # This can be LoadBalancer
